### ISSUE TITLE
Downloads notification issues

### ISSUE THREAD

**Issue by rancidfrog** [kiwibrowser/src.next#151]
A couple of issues regarding notifications.
First, multiple downloads should be grouped so that notifications do not keep jumping around on status bar while downloading:
![](https://i.imgur.com/fAIhNpm.jpg)
The download notification keep switching positions. The only reasonable switch should be when download completes, or perhaps paused.
Next, notification got stuck even though download completed,
Notification:
![](https://i.imgur.com/WM7wLEI.jpg)
clicking on it asks to install since it has already completed.
Downloads:
![](https://i.imgur.com/GcwBBFe.jpg)

**Comment by Efreak** [comment]
> multiple downloads should be grouped so that notifications do not keep jumping around on status bar while downloading:

I'm using a website that does *many* downloads (someone's as many as 15 in a minute) and I also frequently saved images from websites. The inability to group download notifications from kiwi (also chrome) makes my notification drawer useless. At the end of the day, I might have *hundreds* of unwanted download notifications for small 10-500kb images that must all be dismissed individually, while I watch out for unrelated notifications that I *don't* want dismissed. At the same time, I can't simply disable the entire category because I occasionally do have the same use case that's normal on the internet: I'm downloading a file and want to check the progress in my notification bar.

Please *at least* create groups for download notifications created inside installed PWAs; since Android sees these as installed apps, they should get their own notification groups.

**Comment by d3ward** [comment]
@Efreak I understand that this can be annoying, but I don't think Kiwi will get this kind of feature anytime soon, as it's mainly a Chromium/Android issue and not even a bug. 
Instead, I recommend trying external download managers that have more control over notifications, Kiwi fully supports third party download managers.
