### ISSUE TITLE
Support download Edge add-ons natively

### ISSUE THREAD

**Issue by Cyberavater** [kiwibrowser/src.next#159]
It'd be nice if Kiwi could natively download extensions from Edge Add-ons, as some of the extension is missing from Chrome Web Store.

A simple user-agent trick like Opera does, not seems applicable here.

Eg link; https://microsoftedge.microsoft.com/addons/detail/universal-bypass/ckiidekccfgninkobmmofopbbdgdclgg

This issue was referenced in kiwibrowser/src#145

**Comment by Delphox** [comment]
Small update on this one, [due to a change in upstream chromium](https://blog.chromium.org/2020/02/protecting-users-from-insecure.html), the current implementation of downloading Edge extensions directly from edge store doesn't work anymore (the download gets blocked due to mixed content no longer being allowed in chromium).

Until a workaround gets implemented in Kiwi, [you can use this extension as a workaround](https://cdn.discordapp.com/attachments/494814211579445274/867211012901175296/download_edge_store_addons.crx), and use the Download Link option from the hold menu.

**Comment by Delphox** [comment]
Update: workaround above merged onto upstream with https://github.com/kiwibrowser/src.next/pull/285. Should be on next release!

**Comment by d3ward** [comment]
That feature is in Kiwi , is not perfect but is a great solution implemented by @Delphox
