### ISSUE TITLE
Is devtools really necessary?

### ISSUE THREAD

**Issue by K1DV5** [kiwibrowser/src.next#178]
IMO it goes against the intension of being modest and light (which I think is part of the goal.) And if one really needs it, they can use `chrome://inspect` on desktop. I'm not certain but I think it contributes to the app's significant increase in size from the old version.

**Comment by kiwibrowser** [comment]
The devtools is actually an accident / side-effect of better underlying implementation (it's that Kiwi starts to implement so many Desktop APIs, that a lot of the Desktop features start to work)
For example, for devtools, something very subtle, but did you notice that there is right-click contextual menus ? :)
On Desktop they are native, so it's a small detail that Kiwi knows how to handle for example.

The expansion of the size is actually due to the fact that Chromium+Play Store deprecated APK delivery so a lot of the assets are not compressed anymore.
A typical Play Store user gets an .aab file of average 46 to 49 MB, which is relatively reasonable.

The signed APK files are 175 MB, which is really gigantic I agree, but I think the issue is not caused by devtools or added APIs but rather the delivery method (the .apk packaging process itself)

**Comment by K1DV5** [comment]
I see, that clears it up. Thank you for the explanation. Closing.
