### ISSUE TITLE
Changelogs Plz Guys Plz

### ISSUE THREAD

**Issue by gitdebpro** [kiwibrowser/src.next#20]
Hi there dev team plz give us an opportunity to view the changelogs of the latest build so that we might be interested to test the latest build in order to check what's new has been implemented.

Thanks.

**Comment by Lartsch** [comment]
Obviously Kiwi has just been rebased on Chromium v93. So if you need a changelog, just look at the one from Chromium. Kiwi's feature set has not changed with this update.

Also, this is not an issue and additionally a very low quality title. Please close it to keep this repo tidy. @gitdebpro

**Comment by gitdebpro** [comment]
> Obviously Kiwi has just been rebased on Chromium v93. So if you need a changelog, just look at the one from Chromium. Kiwi's feature set has not changed with this update.
> 
> Also, this is not an issue and additionally a very low quality title. Please close it to keep this repo tidy. @gitdebpro 

both kiwi and chromium are same I know but kiwi is different from Chromium in every expect so many features and settings so we need to know what changing are done so far on every update. so No I am not closing it.

Regards.

**Comment by Lartsch** [comment]
"both kiwi and chromium are same I know but kiwi is different from Chromium in every expect" - this does not make any sense, sorry.

As I said, Kiwi's features have NOT changed. All that changed is Chromium as the BASE. So ALL new features are coming from the new Chromium base and you can look up its changelog on your own, if you want to know what changed.

That aside, it's the developers decision to release a changelog. You don't always get it served on a silver plate and need to put some effort in if you are so interested in it. You can look into the commit histories and into Chromium's changelog.

I was asking if you could close this issue because this repo is cluttered with low quality "issues".

No offense intended, just trying to help to keep this Repo tidy.

**Comment by gitdebpro** [comment]
> "both kiwi and chromium are same I know but kiwi is different from Chromium in every expect" - this does not make any sense, sorry.
> 
> As I said, Kiwi's features have NOT changed. All that changed is Chromium as the BASE. So ALL new features are coming from the new Chromium base and you can look up its changelog on your own, if you want to know what changed.
> 
> That aside, it's the developers decision to release a changelog. You don't always get it served on a silver plate and need to put some effort in if you are so interested in it. You can look into the commit histories and into Chromium's changelog.
> 
> I was asking if you could close this issue because this repo is cluttered with low quality "issues".
> 
> No offense intended, just trying to help to keep this Repo tidy.

ok will do
