### ISSUE TITLE
The Chinese webiste （unofficial） of kiwi browser is now online!  kiwi浏览器中文网（非官方）上线了

### ISSUE THREAD

**Issue by muzihuaner** [kiwibrowser/src.next#244]
kiwi浏览器中文网（非官方）上线了！我们会在这里分享最新安装包，应用使用经验，插件分享等等...
https://kiwibrowser.pages.dev/ 
欢迎访问！

The Chinese webiste （unofficial） of kiwi browser is now online!  We will share the latest installation package, application experience, plug-in sharing, etc...
 https://kiwibrowser.pages.dev/
 Welcome to visit！

**Comment by Lartsch** [comment]
I don't think Github Issues are the right place to share such an announcement? This is meant for bug reports and the like, not for news updates. @muzihuaner 

I would suggest to close this issue.

**Comment by kiwibrowser** [comment]
Hello,

Wow you did amazing work with the documentation and the video. I am very impressed!

I will read it, as I am interested to understand what is important to people living in China.
The documentation is especially amazing work.

Congratulations :)
If possible try to put somewhere a bit more obvious it is Unofficial help page, or something like this.

Otherwise, it's really cool, I understand it is very difficult for a China user to speak languages.

I will read in detail, thanks a lot for sharing this @muzihuaner

**Comment by kiwibrowser** [comment]
@muzihuaner Can I share your documentation in the README of the project ? This will it will shine and your work will be useful :)

**Comment by muzihuaner** [comment]
@kiwibrowser YES,YOU CAN😁
