### ISSUE TITLE
Replace the edit button with a clear field button when "Keep address bar content" is checked

### ISSUE THREAD

**Issue by HRudyPlayZ** [kiwibrowser/src.next#308]
Old comment (before realizing Kiwi already fixed most of the issue):

On recent versions, Chrome added the "Search ready omnibox" feature. At first it could be controlled by a flag but it got removed. This feature is the new URL UI that clears the address when you tap, unless you click on the pencil afterwards. It is counter-intuitive.

There's 2 possible solutions for this: Either bring back a way to disable it again, or you can fix this terrible UX design by keeping the URL in edit mode by default (what the pencil button does) and instead replace the pencil button with a clear field button.

The only alternative is either to switch browsers or downgrade to an old chrome/kiwi version.

**Comment by HRudyPlayZ** [comment]
Oh my bad, Kiwi already fixed it. Gotta tell people to do that on the Discord :P

**Comment by HRudyPlayZ** [comment]
Though, you should still add the empty field button instead of the edit one in this mode

**Comment by kiwibrowser** [comment]
However, really thank you for taking the time to write the ticket though;

what you expressed is actually interesting, because it shows that the product has an onboarding / features introduction problem (not you).
Some people may see the same issue, and just run away because they hate it.
So this is a signal that in-product help (IPH) may be needed at this point for this feature.

**Comment by HRudyPlayZ** [comment]
Yeah i hate this feature, and didn't notice it was in the accessibility settings. It is especially annoying with searches as it isn't as simple to dorectly edit your query instead of rewriting it from scratch.

I closed the issue because i forgot Chrome/Kiwi already allowed to clear the field by pressing "x".
I wasn't about to run away from Kiwi, as it's the best mobile browser i've seen. I still don't know why there isn't any extensions on the standard Chrome for Android. Kiwi adds so much good features that it's pretty much a complete upgrade from Chrome.
Firefox would also be an option now that they're restoring mobile extensions compatibility. But it's still slower and not as good as Kiwi :P

**Comment by HRudyPlayZ** [comment]
That being said, i think you should state that there's this option more clearly. I've seen a lot of people frustrated with it on Reddit and other social media.

**Comment by MmyGgithubAaccount** [comment]
I think another way of improving discoverability of kiwi features is to pull them out of Accessibility settings and put them under a separate heading (Kiwi extras/Advanced/whatever). Since kiwi resembles chrome settings a lot, people may not realize there are extra options hidden under accessibility features

**Comment by gnadelwartz** [comment]
second to make kiwi extra features more visible (with additional explanations, may be)

**Comment by kiwibrowser** [comment]
I really think too that Kiwi starts to need onboarding screens (or in-product-help) because a lot of the support is about teaching user where to go.

I am checking if there are WYSIWYG onboarding screens we could do.
I found http://judo.app but it's not really good (unclear pricing, unclear platform, etc).

**Comment by gnadelwartz** [comment]
@kiwibrowser looks like hopefully you already have kiwibrowser.com registered, but .net and .org are registered but not connected.

Therefore kiwibrowser.com would be the palce to host this content ...
