### ISSUE TITLE
Source is not complete/not buildable

### ISSUE THREAD

**Issue by nift4** [kiwibrowser/src.next#317]
After copying this over the normal chromium source, I got many assert errors which have been fixed in old kiwi but aren't in this source. Why is this source not complete? Can you please upload the missing changes?

**Comment by kiwibrowser** [comment]
Hi Nick,

Yes it's +/- normal (not that it's intended, but expected for now).

The /src.next is a toolbox or control center or sandbox for people to build mods, where code is glued on top of Kiwi and on top of Chromium and the assertions are fixed by unpleasant wizardry.
What it does, is take Kiwi, and (conceptually) apply delta patch files on top.

It's an innovative and very opinionated approach. You are taken by the hand, you are in one box, but it's a nice box.

The /src is the 100% reproducible and is 100% built on GitHub (it's maybe one the rare Chromium-based browser as far as I know with the full process online), and a much stronger base / independent if you want to build a full-fledged fork like 2 or 3 browsers did and then you are free to do what you want.

The main problem that src.next tries to address is that the amount of contributors on /src was small, mostly due the complexity and costs for the developers to main or even setup the environment.

Arnaud.

**Comment by DUOLabs333** [comment]
@nift4 It seems that Kiwi is buit by uploading the git repository to a server, which is then built, so it makes sense you can't build it out of the box. It is noted that this is how it is supposed to work ("you can build Kiwi without leaving Kiwi", but it would be nice to have a way to do it completely offline).

**Comment by DUOLabs333** [comment]
@nift4 It seems that Kiwi is buit by uploading the git repository to a server, which is then built, so it makes sense you can't build it out of the box. It is noted that this is how it is supposed to work ("you can build Kiwi without leaving Kiwi"), but it would be nice to have a way to do it completely offline.

**Comment by DUOLabs333** [comment]
@nift4 It seems that there is a workflow titled "Import files", which rebases Kiwi over Chromium, and it is all local, so you can rebase it, and build as normal.

**Comment by nift4** [comment]
> build as normal.

Yeah, the problem is, all changes in the build system files have not been uploaded into the sandbox (atleast I think so) - I'll see how far I can get by adding the changes from src into here when building.

> The /src is the 100% reproducible and is 100% built on GitHub (it's maybe one the rare Chromium-based browser as far as I know with the full process online), and a much stronger base / independent if you want to build a full-fledged fork like 2 or 3 browsers did and then you are free to do what you want.
> The main problem that src.next tries to address is that the amount of contributors on /src was small, mostly due the complexity and costs for the developers to main or even setup the environment.

I wondered if it can't be both, I'll try to play with build system and sandbox in a fork, maybe we can make the sandbox buildable.
