### ISSUE TITLE
After googling for a business, "call" button does nothing

### ISSUE THREAD

**Issue by alleluia20** [kiwibrowser/src.next#325]
When you google for a business (shop, doctor, etc), Google typically returns a summary of such business, which includes a "call" button. When you press on it on other browsers, the call app (the regular "telephone") opens with the phone number. If you were in private browsing, a confirmation is asked.

On Kiwi browser, pressing on the call button does nothing. I just briefly see the progress bar completing, but that is all.

Regards.

**Comment by DUOLabs333** [comment]
Do you have "open in external applications" enabled?

**Comment by kiwibrowser** [comment]
I just tested with all the default Kiwi settings but this works for me, could you tell a bit more about what phone you have ?

**Comment by DUOLabs333** [comment]
Doesn't work for me -- I have "open in external applications" enabled. Phone is a Pixel 5 with stock Android.

**Comment by kkuhle** [comment]
I experience this behavior as well after a fresh install of Kiwi Browser with no settings changed.

I am on a OnePlus 6T running HavocOS on Android 11 (`havoc_fajita-userdebug 11 RQ2A.210405.005 eng.havocc.20210424.074214 release-keys`)

This may be a stretch, but there are some Google applications that register my phone as a Pixel 5 (such as Google Find Device or Google Photos)

I wonder what kind of device @alleluia20 has?

**Comment by alleluia20** [comment]
It is a Xiaomi. But, again, the call button works with other browsers on
the same device.

**Comment by Delphox** [comment]
> I just tested with all the default Kiwi settings but this works for me, could you tell a bit more about what phone you have ?

It's a problem with android 11 actually. I've upgraded recently to android 11 and it's having trouble connecting to external apps. Even app logins that use CCT (such as Zoom when you try to login with Google account) is broken. I'd say this is a pretty major issue considering the Android 11 market share is growing fast and should overtake 10 soon.

And yea it works fine on 10 and under, which is why you may not be experiencing it.

**Comment by kiwibrowser** [comment]
I was thinking and maybe I have a theory if you think about Android 11;
Could it be because there are new privacy rules on Android 11 which causes applications to not be able to enumerate external apps and by extension call them ?
If this is the case, then it could explain why I don't have the issue, and the solution would be to ask Google (again...) for an exception for Kiwi Browser in Play Store to get the list of installed apps

**Comment by DUOLabs333** [comment]
Will you have this problem if you don't distribute via the Play Store? If so, then we may have to think about distributing manually on GitHub or F-droid. This would also allow us to have background play on YouTube.

**Comment by Delphox** [comment]
That's strange cuz I thought apps didn't need explicit package names to call external apps, they'd just call a protocol and relay the content to it, then Android would take care of the rest. But then again I'm not an android dev lol, so idk. But it's what would make sense to me.

**Comment by kiwibrowser** [comment]
https://support.google.com/googleplay/android-developer/answer/10158779?hl=en

**Comment by kkuhle** [comment]
That is an interesting requirement that they've changed in Android 11, and maybe related to this issue, but I'm not sure I'm understanding it correctly.  The other thing that gets me is the call button works for me if I use the older version of KiwiBrowser:
```
Application version
Git210216Gen570536402 (Updated 1 minute ago)
Operating system
Android 11.0.0; ONEPLUS A6013 Build/RQ2A.210405.005
```

- or the latest "classic" version (downloaded from `kiwibrowser/src`):
```
Application version
Git210814Gen1130924267 (Updated 22 seconds ago)
Operating system
Android 11.0.0; ONEPLUS A6013 Build/RQ2A.210405.005
```
However, if I use any KiwiBrowser that runs on Chromium 93.x, the call button does not work.

The other Chromium browsers I've tested (Edge, Brave) are on Chromium 92.x.  Is it at all possible that Google broke something for 3rd party browsers in the 93.x+ builds since the call button works in Android 11 for the older KiwiBrowser and the other slightly older Chromium builds (Edge, Brave).

Is it a complicated process to put the current KiwiBrowser code on a slightly older version of Chromium to see if an older version prevents this broken functionality?

**Comment by kkuhle** [comment]
I noticed this is fixed today from the update on September 21st.  Although I noticed the appearance of the browser looks like the classic version to me (maybe I am imagining it), so I am wondering if we went back to API Level >30?  I'm not complaining in any way and I'm happy that I can use Kiwi again with this bug not being present in the current version.

**Comment by Delphox** [comment]
> I noticed this is fixed today from the update on September 21st. Although I noticed the appearance of the browser looks like the classic version to me (maybe I am imagining it), so I am wondering if we went back to API Level >30? I'm not complaining in any way and I'm happy that I can use Kiwi again with this bug not being present in the current version.

Nope it's actually targeting API 32. Google gave Arnaud authorization so he added the permission back (you can see on All Permissions on the package manager it has QUERY_ALL_PACKAGES). As for looking more classic, it did have an updated icon pack recently but I think it was before that.

**Comment by kkuhle** [comment]
Shouldn't this be marked as fixed?

**Comment by kiwibrowser** [comment]
Yes that's right, thank you @kkuhle :)
