### ISSUE TITLE
Kiwi Browser both google play and non play version in BlueStacks always Force Close(crash in splash screen)

### ISSUE THREAD

**Issue by quaggalinux** [kiwibrowser/src.next#351]
**Describe the bug**
Kiwi Browser both google play and non play version in BlueStacks always Force Close(crash in splash screen)

**To Reproduce**
install Kiwi Browser in google play or direct install non play version in BlueStacks(android Emulator) windows 10. BlueStacks is up to date version. Upon opening Kiwi Browser the app always Force Close(crash in splash screen)

**Expected behavior**
Does not happen in lastest old version Kiwi Browser(Git210216Gen570536402). But it only happens in 
new version Kiwi Browser 9x. Also the Chrome for android up to date version still work.

**windows 10  BlueStacks(android Emulator) **
 - Kiwi Browser Version [ 93.0.4577.39 ]

**Comment by kyoyacchi** [comment]
Hmm, it works for me. (Not BlueStacks)
It may be fixed in next version or i don't know it maybe not relative with kiwi browser. 

![Screenshot_2021-08-20-00-04-27](https://user-images.githubusercontent.com/63583961/130143736-52689268-0268-41ac-80d6-09a2f4c5ca11.png)

**Comment by kiwibrowser** [comment]
Hello,

To use Kiwi in an emulator, you need to use the -x86.apk build, otherwise the app is going to crash.

This is because the engine of Chromium (not the user interface though!) has to be built according to the architecture of the processor you are using.
-arm or -x86 are the architecture of the processor.
-arm is typically a mobile device, and -x86 typically a desktop PC.

Architecture means the language that the processor can understand.

It's a bit like speaking Japanese to a German, and vice-versa, they wouldn't understand each other easily.

If you see Kiwi starting up, it means the UI starts to load, and that it crashes when loading the engine, and that'd mean it's really indeed the architecture situation.

**Comment by gnadelwartz** [comment]
shouldn't an emulator select the correct architecture when installing from play store?

**Comment by kiwibrowser** [comment]
True about the Play Store, but I thought BlueStacks didn't have Play Store support ?
I have intuition the person installed -arm64.apk by habit, but let's see

@quaggalinux do you remember which APK you have been trying to install ?

**Comment by gnadelwartz** [comment]
blue stack seems to have direct play store support https://support.bluestacks.com/hc/en-us/articles/360057712191-How-to-install-an-app-on-BlueStacks-5

**Comment by quaggalinux** [comment]
> 
> 
> True about the Play Store, but I thought BlueStacks didn't have Play Store support ?
> I have intuition the person installed -arm64.apk by habit, but let's see
> 
> @quaggalinux do you remember which APK you have been trying to install ?

I jus
