### ISSUE TITLE
Tab Switcher button/UI on Tablets

### ISSUE THREAD

**Issue by Mav3r1x** [kiwibrowser/src.next#387]
On Android tablets, chrome uses tabstrip similar to that in desktop version. However with dozens of tabs open, this is very frustrating to use on Android tablets.
I would like to see the addition of tab switcher button/UI on Kiwi running on Android tablet.

**Comment by kakhulu31** [comment]
+1
I know that having <600 dpi is not explicitly required to use phone ui and vise versa since foldable phones can ignore this rule with enable-android-layout-change-tab-reparenting flag disabled
Currently kiwi is almost unusable on tablets as any chrome based browser  so this option seems to be very beneficial

**Comment by Mav3r1x** [comment]
Chrome itself introduced this feature in v97 beta. It can be turned on via a flag. So I'm closing this issue.
