### ISSUE TITLE
New Tab Page Extensions

### ISSUE THREAD

**Issue by 1John419** [kiwibrowser/src.next#439]
Example manifest.json:
```
{
    "chrome_url_overrides": {
       "newtab": "new-tab.html"
    },
    "manifest_version": 2,
    "name": "new-tab",
    "version": "1.0"
 }
``` 
It appears that Kiwi does not support the chrome_url_overrides newtab manifest entry.

I have tested this with a custom extension I wrote and several similar extensions in the Web Store.  These extensions work as expected in Chromium (Windows and Linux). These extensions install successfully in Kiwi, but have no effect on the New Tab Page.

I don't know if this is a bug, an oversight, or an intentional omission...

**Comment by gnadelwartz** [comment]
this may because kiwi use an own newtab implementation, you may try if it's working when original Chrome newtab is set as new tab page chrome://newtab

**Comment by 1John419** [comment]
Interesting. These extensions do work when chrome://newtab url is entered manually (as opposed to tapping New tab from the menu). Is there a way to configure Kiwi to use the original Chrome newtab instead?

**Comment by gnadelwartz** [comment]
chrome://newtab as Startpage?

**Comment by 1John419** [comment]
If tapping New tab from the triple dot menu is the Startpage, then yes.

**Comment by kiwibrowser** [comment]
What determines which homepage should be opened is actually happening very early, directly inside the Android / Java-part application, way way before the WebKit/Blink engine starts to be loaded.

This is because on Android, in the typical Chromium setup, the new tab page is a native Java (Android) page that can be directly loaded without having to wait for the WebKit/Blink engine to load.

To add support for 3rd party pages, I guess a solution would be to wait for the WebKit / Blink engine (including extensions) to be loaded, and then interrogate the engine which homepage to load and then only to load it.

A good idea could be to add a custom UI to ask the user the permission to change its homepage as well if we want to do it right (or simply insist on that point at the installation time of the extension ?).

All that being said, in Kiwi, you can set any homepage of your choice, if you go to the Settings (including chrome/kiwi-extension:// URLs)

**Comment by 1John419** [comment]
Ah, I normally have the Homepage turned off. If I turn it on and set it to open chrome://newtab, these extensions work as expected. Definitely the quickest, least intrusive, way to enable this type of extension. I see no need to even consider modifying Kiwi, when such a simple fix is available. Thank you!

**Comment by karl-pae** [comment]
Should this issue be closed. OP has found the fix.
