### ISSUE TITLE
Back button closes the browser instead of the tab

### ISSUE THREAD

**Issue by Mav3r1x** [kiwibrowser/src.next#485]
If you open a new tab and then press back button on the nav bar, instead of closing the newly opened tab and going to the last tab, it closes the browser. This is a very weird behavior and often results in accidentally closing the browser.

**Comment by Mav3r1x** [comment]
@kiwibrowser I would love to know if this is intentional or a bug?

**Comment by MooShuOrc** [comment]
I feel bad that you've been ignored for weeks.

I'm not a developer, so I can't fix it, but I can tell you that Kiwi has behaved this way for years. I can't think of any reason why it would be intentional, but there's also no way that it's gone unnoticed all these years.

Maybe just think of it as "personality."

**Comment by kiwibrowser** [comment]
I struggled to understand the joke (too early in the morning I guess) :D
The Kiwi's personality has changed in the last week actually, I issued a fix last week so normally it should be fine now.
The issue was that extensions, when they opened a new window, by default they were having this behaviour (back button = exit), so I changed it to "back button = previous page".

Is it ok for you now @Mav3r1x or you still see such cases of "back button = exit" that are not coherent ?

Thanks,

**Comment by Mav3r1x** [comment]
@kiwibrowser it seems to be working ok now. Thanks for the quick fix!

**Comment by kiwibrowser** [comment]
Thank you for the confirmation
