### ISSUE TITLE
Is there a version of the Kiwi browser that uses the Android system WebView?

### ISSUE THREAD

**Issue by Doddddd** [kiwibrowser/src.next#510]

**Comment by gnadelwartz** [comment]
No, as kiwi is based 9n google chromium its almost impossible to replace renderer with WebView

**Comment by Doddddd** [comment]
> 不，因为 kiwi 是基于 google chromium 的，所以绝对用 WebView 替换渲染器

Thank you

**Comment by pc00per** [comment]
But default Android webview that shipped on all Android devices (com.android.webview) is open source. There are even Webview based browsers which are lightweight. Kiwi is possible to do such way. Because right now, kiwi ships with the same webview like Chrome has it's own trichrome library, which almost feels duplicate to me.
