### ISSUE TITLE
Remove password strip above keyboard

### ISSUE THREAD

**Issue by pc00per** [kiwibrowser/src.next#730]
I personally use Bitwarden so need of [password suggestion strip](https://user-images.githubusercontent.com/83843264/195519227-51dfeb21-4e83-4292-8d5f-4dc9c66ea685.png) .
It interferes with search provider auto suggestions. Provide us a userside option to disable it if possible.

**Comment by bershanskiy** [comment]
This is not a Kiwi-specific bug, it comes from Chromium and had already been fixed in Chromium 107 and up.

I noticed this bug back on Google Chrome/Chromium 105, but it was resolved in Chrome 107 (tested Chrome Beta 107.0.5304.36). @pc00per The newest Kiwi on GitHub is based on Chromium 107, so you can install it and this bug will be fixed. Word of caution: it is still pre-release testing build, so might contain some regressions (so far, I personally haven't found any).

@netrunner-exe wrote:
> You can try just turning off password saving and automatic login in Kiwi options.

This does not work (tested on Google Chrome 106.0.5249.79 and Kiwi 105.0.5195.33).

**Comment by pc00per** [comment]
Great. So, on webview v106 or greater it's been fixed ?
I'm on gps version 105 instead of GitHub pre releases. So can't replace, as it'll be a conflict.

**Comment by pc00per** [comment]
UPDATE
Just moved to Bromite System WebView (still on v105) & it's gone.

**Comment by bershanskiy** [comment]
> Great. So, on webview v107 or greater it's been fixed ?

I think so, however I haven't tested on WebView 107 explicitly. I'll try to build and test if I have time.

**Comment by bershanskiy** [comment]
@pc00per I verified that this if fixed on Kiwi 107.0.5304.66 which was already released on Google Play Store.

**Comment by pc00per** [comment]
@bershanskiy Yup. I can verify it too. It's clean now.
