### ISSUE TITLE
last version, extension-smartup doesn't work

### ISSUE THREAD

**Issue by elsns** [kiwibrowser/src.next#75]
last version, extension-smartup doesn't work

**Comment by Lartsch** [comment]
Kiwi developers can only give limited support for extensions, I think. Some issues can only be fixed by the extension developer, not by Kiwi. Ultimately. some extensions will probably never work.

Also, you need to elaborate on what exactly isn't working and what you would expect instead. Also: did the extension work with earlier versions of Kiwi?

Issues like this are not helpful. @elsns

**Comment by karl-pae** [comment]
Not properly explained. @d3ward should this be closed ?

**Comment by d3ward** [comment]
> Not properly explained. @d3ward should this be closed ?
Yes.

@elsns Consider making a new issue with detailed info and using the bug template
