### ISSUE TITLE
Use Revancedapp to patch Chrome Android 

### ISSUE THREAD

**Issue by thegravity98** [kiwibrowser/src.next#778]
(ask) Is it possible for you to add a Revanced patch that enables chrome extension support for chrome Android?

**Comment by admin-elvistrujanovic** [comment]
> (ask) Is it possible for you to add a Revanced patch that enables chrome extension support for chrome Android? 

They don't want even to create Xposed framework module for patching chromium browsers at all for many reasons so, why will they even create their tool for patching kiwi unlocked ability into any chromium browsers - that would of course include Original Google Chrome modification but it's not easy at all - especially because most those browsers like Google Chrome and Google Chrome itself are closed source - only chromium pure base are unlocked source (open source).
