### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [kiwibrowser/src.next#844]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by kiwibrowser** [comment]
Hey,

I added the setting, so now it's possible to report issues privately if necessary,
Cool to see such feature.

In Kiwi there is relatively little code that is sensitive to security issues (since Kiwi is mostly UI-changes on top of Chromium), so if you caught anything it's most likely an issue in Chromium (that would then be fixed upstream), in all cases I'll be happy to take a look and check (if this is not already fixed obviously).

Thanks again !
Arnaud.

**Comment by kiwibrowser** [comment]
Closing as waiting in pm
