### ISSUE TITLE
Why release garbage full of bigs?

### ISSUE THREAD

**Issue by reset77** [kiwibrowser/src.next#940]
**Describe the bug**
Garbage full of bugs

**To Reproduce**
Just use kiwi and you find its garbage full of bugs

**Expected behavior**
Test it before release

**Screenshots**
Fuck this garbage unusable browser

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 7]
 - Android Version : [e.g. A11 ]
 - Kiwi Browser Version [ e.g. 90.0.4577.17 ]

**Additional context**

**Comment by d3ward** [comment]
Thank you for taking the time to provide useless feedback. 
If the current state of the Kiwi browser is not to your liking, I understand, but there are ways and ways of reporting it, and yours is wrong. Don't like it? No patience ? .... don't use it, because nobody's forcing you to. 

Kiwi browser version on Github is a early access release. This means that it is still being developed and tested, and users are providing feedback to help improve it before is released on the Play Store. Sometimes there are bugs on Playstore too but hey , check how many devices, configurations and Android versions are out there.

while I understand your frustration with the issues you are experiencing, it would be helpful if you could provide more detailed information about the bugs you are experiencing instead of the "garbage" issue you opened.
